### ISSUE TITLE
Creating User Table

### ISSUE THREAD

**Issue by dg01d** [aaronpk/Compass#17]
The documentation does not provide details on creating a database 'user-table'

Following the [Lumen documentation](https://laravel.com/docs/5.5/migrations) I created a users_table; however it does not appear that this has been effective, as compass now errors after indieauth with:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'url' in 'where clause' (SQL: select * from `users` where `url` = https://example.com/ limit 1)`

Inspection of the table `users` does not show an index for `url`

**Comment by aaronpk** [comment]
If you run the migrations it will create all the tables as needed. I've updated the instructions to make this more clear.
