### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by theprivateer** [aaronpk/Compass#2]
Really like what this project is doing - however I'm unable to get up and running as there appear to be a number of database migrations missing (presumably as this project was built on top of an existing database structure).

Is there any way to get an indication of the pre-existing database schema so that I can bootstrap my own copy of the project?

Thanks.

**Comment by aaronpk** [comment]
Sorry about that! I'm not sure why the initial database creation migrations weren't in the repo. 

I've dumped a copy of the latest schema here: https://github.com/aaronpk/Compass/blob/master/compass/database/schema.sql
