### ISSUE TITLE
settings redirects to map

### ISSUE THREAD

**Issue by mvexel** [aaronpk/Compass#27]
This used to work, but I moved the site to another server and now it doesn't. 

I log in, select a database, see the map screen. I click on 'settings' but instead of being taken to the settings, I get redirected to the database selection screen. 

If I create a brand new database, all works great..

**Comment by nitinthewiz** [comment]
What URL does it point to when you hover on the Settings link?

**Comment by aaronpk** [comment]
This sounds like a permissions issue. I made it redirect to the home page if the user who's logged in doesn't have access. You might need to go into the database to tell it the current user account has access to the database you're trying to look at.
