### ISSUE TITLE
Safe to empty storage/framework/cache ?

### ISSUE THREAD

**Issue by jeremycherfas** [aaronpk/Compass#45]
I’ve been running low on disk space on my server and have discovered that `storage/framework/cache` on my install of Compass is up to 15G.

Are all those files necessary if I have all the daily `.txt` files in the `data` folder?

**Comment by aaronpk** [comment]
that's surprising! I don't even know what it could be caching that would be that large. It should be safe to delete everything in the cache folder.

**Comment by jeremycherfas** [comment]
Thanks. I deleted everything and it immediately started recreating folders and files.

Each file contains something like `1653226679i:1;` or `1653226679i:1;` (I sampled only two in the same folder. They look to be identical! In another folder, the file contains `1653226680i:1;`

`lumen.log` does not seem to contain anything interesting, only `Device sent current location` and occasional records of a Trip.

No other obvious log files I can see. If there's anything else I can do, please let me know.

I'll close, for now, and keep an eye on the size of that folder and delete all files in it when I need to.
