### ISSUE TITLE
500 when Atlas is unreachable

### ISSUE THREAD

**Issue by sebsel** [aaronpk/Compass#7]
From time to time I get an error in de GPS logger, and `/storage/logs/lumen.log` says:
`lumen.ERROR: ErrorException: Trying to get property of non-object in /var/www/compass/compass/app/Http/Controllers/Api.php:274`

This is because `$geocode`, from `self::geocode()` is not an object in:

```php
       $geocode = self::geocode(['latitude'=>$last_location['geometry']['coordinates'][1], 'longitude'=>$last_location['geometry']['coordinates'][0]]);
       $response['geocode'] = [
         'full_name' => $geocode->full_name,
         'locality' => $geocode->locality,
         'country' => $geocode->country
       ];
```

And I think that is because `self::geocode()` returns a `json_decode()` of the cURL response to Atlas. 

After a few tries Atlas returns something again, and the party goes on.

**Comment by aaronpk** [comment]
I decided to just disable this geocoding step. when storing locations. I think it was causing additional problems as well. I'll add back the geocoding in some other place in the iOS app.
